# sample docker build command  - docker build -f src/.template.base/webapp-wasm/src/Client/dockerfile -t client-blazor-wasm .
FROM mcr.microsoft.com/dotnet/nightly/sdk:8.0.100 AS build
ARG BUILD_CONFIGURATION=Release
ARG Build_Version=1.0.0
WORKDIR /src
COPY ./src .
# Adjust the path accordingly to reflect your actual project directory.
RUN dotnet restore "/src/.template.base/webapp-wasm/src/Client/dockerfile" 
RUN dotnet publish "/src/.template.base/webapp-wasm/src/Client/dockerfile" -c Release -o /app/publish /p:UseAppHost=false

FROM nginx:latest AS final
WORKDIR /usr/share/nginx/html
COPY --from=build /app/publish/wwwroot .
COPY src/Web/MediaToolkit.Web.WebAssembly/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
EXPOSE 443