# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Template To Nuget

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build ./src/templates.csproj --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test ./src/templates.csproj --no-build --verbosity normal
    - name: Pack
      run: dotnet pack ./src/templates.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push Nuget Package
      run: dotnet nuget push Obaki.Templates.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
    
